### ISSUE TITLE
decimals wrong

### ISSUE THREAD

**Issue by GuenterBernd** [cochraef/LuaLaTeX-CAS#10]
The result output of

\begin{CAS}%
vars('y','x')%
 y = ((0.01) * 5):autosimplify()%
\end{CAS}%

$\print{y}$

is 1/2, this is not correct.

Please can you fix this, thank you very much.

**Comment by timothy-all** [comment]
This should be fixed shortly (it's the same bug that caused problems with decimals before... I'm going to push these fixes to CTAN within a day, so it should be fixed soon!)

**Comment by GuenterBernd** [comment]
Thank you very much for your excellent work.

**Comment by timothy-all** [comment]
Version 1.0.2 (available now on CTAN) should fix this issue.
