### ISSUE TITLE
decimal values wrong

### ISSUE THREAD

**Issue by GuenterBernd** [cochraef/LuaLaTeX-CAS#5]
The output of this file ist:
21
201/10
1

What ist wrong?
Thanks for help.

\documentclass[a4paper,10pt]{article}
\usepackage{luacas}

\begin{document}
\begin{CAS}
 vars('x','y','z')
 x = (20.1):autosimplify()
 y = (20 + 1/10):autosimplify()
 z = (0.1):autosimplify()
\end{CAS}

$\print{x}$

$\print{y}$

$\print{z}$

\end{document}

**Comment by timothy-all** [comment]
Thanks for pointing out this bug! I think the issue is the the definition of Integer.ceillog -- I should have a fix soon

**Comment by GuenterBernd** [comment]
Thank you very much
