### ISSUE TITLE
Multiplication not kommutativ

### ISSUE THREAD

**Issue by GuenterBernd** [cochraef/LuaLaTeX-CAS#6]
In luacas the result of 2*0.5 is not the same as ov 0.5*2

Thanks for fixing that

**Comment by timothy-all** [comment]
It seems we have a few more bugs to squash with decimal expressions. I don't suspect this is hard to fix either, but in the meantime, enclosing decimals in parentheses seems to not cause the error (e.g. 2*(0.5) == (0.5)*2).
