### ISSUE TITLE
Equation solution not correct

### ISSUE THREAD

**Issue by GuenterBernd** [cochraef/LuaLaTeX-CAS#7]
\begin{CAS}
 vars('x')
 f = Equation(2*x-1,1*x)
 r = roots(f.lhs() - f.rhs())
\end{CAS}
 
 $x=\lprint{r}$

gives the correct solution x=1, but when I change the 1*x to x:

\begin{CAS}
 vars('x')
 f = Equation(2*x-1,x)
 r = roots(f.lhs() - f.rhs())
\end{CAS}
 
 $x=\lprint{r}$

**there is no output.**

**Comment by timothy-all** [comment]
I think the issue here is that you are using f.lhs() and f.rhs() when you should be using f.lhs and f.rhs (since lhs and rhs are fields, not methods). So for example:

\begin{CAS}
vars('x')
f = Equation(2*x-1,x)
r = roots(f.lhs - f.rhs)
\end{CAS}
\[ x = \lprint{r} \] 

produces the expected output.
